// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDL-iZNh99OgAe0vrhN9uDH3v52C3zfFI',
    appId: '1:199730167901:android:3dda3fa69c7e634f218db4',
    messagingSenderId: '199730167901',
    projectId: 'riverpot-firestore-strea-66db9',
    storageBucket: 'riverpot-firestore-strea-66db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3vbgNvrN4AoBTIZXwR9QoSlK8ixnNcU',
    appId: '1:199730167901:ios:1c6c293853b1c903218db4',
    messagingSenderId: '199730167901',
    projectId: 'riverpot-firestore-strea-66db9',
    storageBucket: 'riverpot-firestore-strea-66db9.appspot.com',
    iosClientId: '199730167901-38eh3kr2j437tej5vi7suqbl4e9s18pi.apps.googleusercontent.com',
    iosBundleId: 'site.mtcoding.riverpotFirestoreStream',
  );
}
